# bot/database/methods/__init__.py
# Explicit re-exports — avoids wildcard namespace pollution.

from packages.database.methods.create import (
    create_user,
    create_item,
    add_values_to_item,
    create_category,
    create_operation,
    create_pending_payment,
    create_referral_earning,
    credit_signup_referral_bonus,
    create_role,
    create_promo_code,
    add_to_cart,
    create_review,
)
from packages.database.methods.read import (
    check_user,
    check_user_cached,
    check_role,
    check_role_cached,
    check_category,
    check_category_cached,
    check_value,
    get_item_info,
    get_item_info_cached,
    get_goods_info,
    get_bought_item_info,
    get_all_users,
    get_all_roles,
    get_role_by_id,
    get_role_id_by_name,
    get_roles_with_max_perms,
    get_roles_with_user_counts,
    get_user_count,
    get_user_count_cached,
    get_user_referral,
    get_referral_earnings_stats,
    get_one_referral_earning,
    get_blocked_user_ids,
    get_cart_items,
    get_cart_count,
    get_promo_code,
    get_item_avg_rating,
    get_user_review,
    has_purchased_item,
    select_admins,
    select_admins_cached,
    select_max_role_id,
    select_count_items,
    select_count_goods,
    select_count_categories,
    select_count_bought_items,
    select_unique_buyers,
    select_avg_order,
    select_all_orders,
    select_all_operations,
    select_today_orders,
    select_today_orders_count,
    select_today_operations,
    select_today_users,
    select_users_balance,
    select_user_items,
    select_user_operations,
    select_item_values_amount,
    select_item_values_amount_cached,
    select_bought_item,
    select_blocked_users_count,
    check_user_referrals,
    count_users_with_role,
    check_role_name_by_id,
    validate_promo_for_item,
    invalidate_user_cache,
    invalidate_item_cache,
    invalidate_category_cache,
    invalidate_stats_cache,
    invalidate_rating_cache,
)
from packages.database.methods.update import (
    set_role,
    update_balance,
    update_user_discount,
    update_item,
    set_user_blocked,
    is_user_blocked,
    update_category,
    update_role,
    toggle_promo_code,
    reset_account_discount,
)
from packages.database.methods.delete import (
    delete_item,
    delete_only_items,
    delete_item_from_position,
    delete_category,
    delete_role,
    delete_promo_code,
    remove_from_cart,
    clear_cart,
    delete_review,
)
from packages.database.methods.lazy_queries import (
    query_categories,
    query_items_in_category,
    query_user_bought_items,
    query_all_users,
    query_items_in_position,
    query_user_referrals,
    query_referral_earnings_from_user,
    query_all_referral_earnings,
    query_promo_codes,
    query_user_operations_history,
    query_item_reviews,
)
from packages.database.methods.transactions import (
    buy_item_transaction,
    process_payment_with_referral,
    admin_balance_change,
    redeem_balance_promo,
    checkout_cart_transaction,
    buy_reseller_item_transaction,
    refund_reseller_purchase,
    confirm_reseller_purchase_success,
)
from packages.database.methods.cache_utils import safe_create_task
from packages.database.methods.audit import log_audit

__all__ = [
    # create
    "create_user", "create_item", "add_values_to_item", "create_category",
    "create_operation", "create_pending_payment", "create_referral_earning",
    "credit_signup_referral_bonus",
    "create_role", "create_promo_code", "add_to_cart", "create_review",
    # read
    "check_user", "check_user_cached", "check_role", "check_role_cached",
    "check_category", "check_category_cached", "check_value",
    "get_item_info", "get_item_info_cached", "get_goods_info",
    "get_bought_item_info", "get_all_users", "get_all_roles", "get_role_by_id",
    "get_role_id_by_name", "get_roles_with_max_perms", "get_roles_with_user_counts",
    "get_user_count", "get_user_count_cached", "get_user_referral",
    "get_referral_earnings_stats", "get_one_referral_earning", "get_blocked_user_ids",
    "get_cart_items", "get_cart_count", "get_promo_code",
    "get_item_avg_rating", "get_user_review", "has_purchased_item",
    "select_admins", "select_admins_cached", "select_max_role_id",
    "select_count_items", "select_count_goods", "select_count_categories",
    "select_count_bought_items", "select_unique_buyers", "select_avg_order",
    "select_all_orders", "select_all_operations", "select_today_orders",
    "select_today_orders_count", "select_today_operations", "select_today_users",
    "select_users_balance", "select_user_items", "select_user_operations",
    "select_item_values_amount", "select_item_values_amount_cached", "select_bought_item",
    "select_blocked_users_count", "check_user_referrals", "count_users_with_role",
    "check_role_name_by_id", "validate_promo_for_item",
    "invalidate_user_cache", "invalidate_item_cache", "invalidate_category_cache",
    "invalidate_stats_cache", "invalidate_rating_cache",
    # update
    "set_role", "update_balance", "update_item", "set_user_blocked",
    "is_user_blocked", "update_category", "update_role", "toggle_promo_code",
    # delete
    "delete_item", "delete_only_items", "delete_item_from_position",
    "delete_category", "delete_role", "delete_promo_code",
    "remove_from_cart", "clear_cart", "delete_review",
    # lazy_queries
    "query_categories", "query_items_in_category", "query_user_bought_items",
    "query_all_users", "query_items_in_position", "query_user_referrals",
    "query_referral_earnings_from_user", "query_all_referral_earnings",
    "query_promo_codes", "query_user_operations_history", "query_item_reviews",
    # transactions
    "buy_item_transaction", "process_payment_with_referral", "admin_balance_change",
    "redeem_balance_promo", "checkout_cart_transaction",
    "buy_reseller_item_transaction", "refund_reseller_purchase",
    "confirm_reseller_purchase_success",
    # utils
    "safe_create_task",
    # audit
    "log_audit",
]
