"""Add name_override icon_emoji to reseller_products

Revision ID: 3532d77c496b
Revises: acc68c736908
Create Date: 2026-08-15 06:11:16.685126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3532d77c496b'
down_revision: Union[str, None] = 'acc68c736908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = sa.inspect(op.get_bind())
    if 'reseller_products' in inspector.get_table_names():
        cols = {col['name'] for col in inspector.get_columns('reseller_products')}
        if 'name_override' not in cols:
            op.add_column('reseller_products', sa.Column('name_override', sa.String(length=256), nullable=True))
        if 'icon_custom_emoji_id' not in cols:
            op.add_column('reseller_products', sa.Column('icon_custom_emoji_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = sa.inspect(op.get_bind())
    if 'reseller_products' in inspector.get_table_names():
        cols = {col['name'] for col in inspector.get_columns('reseller_products')}
        if 'icon_custom_emoji_id' in cols:
            op.drop_column('reseller_products', 'icon_custom_emoji_id')
        if 'name_override' in cols:
            op.drop_column('reseller_products', 'name_override')
    # ### end Alembic commands ###
