"""Add cost_price

Revision ID: 3f84f5064bc4
Revises: 22526993094e
Create Date: 2026-07-24 12:40:27.681714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f84f5064bc4'
down_revision: Union[str, None] = '22526993094e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bought_goods', sa.Column('cost_price', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    op.add_column('goods', sa.Column('cost_price', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'cost_price')
    op.drop_column('bought_goods', 'cost_price')
    # ### end Alembic commands ###
