"""add icon_custom_emoji_id

Revision ID: c0ba4bb64313
Revises: f8b2d3a1c5e7
Create Date: 2026-08-14 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0ba4bb64313'
down_revision: Union[str, None] = 'f8b2d3a1c5e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('icon_custom_emoji_id', sa.String(length=64), nullable=True))
    op.add_column('goods', sa.Column('icon_custom_emoji_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'icon_custom_emoji_id')
    op.drop_column('categories', 'icon_custom_emoji_id')
    # ### end Alembic commands ###
